on:
  push:
    branches:
    - main

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 21
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOYMENT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          keyscanresult=`ssh-keyscan -p ${{ secrets.DEPLOYMENT_SSH_PORT }} -t ed25519 ${{ secrets.DEPLOYMENT_SSH_HOST }} 2> /dev/null`
          echo $keyscanresult >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: |
          rsync -ravz -e "ssh -i $HOME/.ssh/id_ed25519 -p ${{ secrets.DEPLOYMENT_SSH_PORT }}" --delete build/ ${{ secrets.DEPLOYMENT_SSH_USERNAME }}@${{ secrets.DEPLOYMENT_SSH_HOST }}:
